services:
  kobweb:
    build: .
    ports:
      - "3333:3333"  # Bind the container's port 3333 to the host's port 3333
    environment:
      - PORT=3333  # Set the environment variable for the port inside the container
    volumes:
      - kobweb_data:/app/site  # Use a Docker volume for persistence and mount it to /app/site

volumes:
  kobweb_data:
    driver: local
